# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: holidays
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev #spring.profiles.active#
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:holidaysapi;DB_CLOSE_DELAY=-1
        name:
        username: holidaysApp
        password:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    